name: Download a file from S3

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Copy a file from s3
      uses: prewk/s3-cp-action@v2
      with:
        aws_access_key_id: ""
        aws_secret_access_key: ""
        aws_session_token: ""
        source: './'
        dest: 's3://sewunetabebaw.com/'
        flags: --recursive
